### ISSUE TITLE
Consider mentioning URL Publish and Unpublish

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/publishcontent#1]
In https://github.com/backdrop-contrib/url_unpublish I mention this project and the differences.  It may be helpful to users if there was a comparable comparison here.

**Comment by bugfolder** [comment]
Sure. How about this for an addition to the README:

Similar Modules
----------------

* The [URL Publish and Unpublish](https://backdropcms.org/project/url_unpublish) module provides some similar functionality, creating URLs that you can use to publish and unpublish content.

**Comment by yorkshire-pudding** [comment]
Yes - that's fine.

There's a need to dedruplify the readme under installation. Also there is a link to the wiki that doesn't exist.

**Comment by bugfolder** [comment]
Merged into HEAD. Thanks, @yorkshire-pudding!
